Fix application_controller invalid system call
ClusterLabs/hawk pull request #227
Opened 2021-02-02 07:32 UTC by Alix82

This partially reverts 2fe6369e6f70a0fe2f9d8ab884ae6bb4606f6f39

Otherwise, hawk crashes with 

 bundle[14597]: #<NameError: undefined local variable or method `attrd_updater' for

2021-02-02 08:52 UTC, MalloZup requested changes
thank you All we need for this PR `system` instead of `%x`

If you need more rationale on this, contact me via our chat.

2021-02-02 08:53 UTC, MalloZup commented
see https://github.com/ClusterLabs/hawk/commit/2fe6369e6f70a0fe2f9d8ab884ae6bb4606f6f39#commitcomment-46387864

2021-02-10 10:51 UTC, MalloZup commented
closing in favor of https://github.com/ClusterLabs/hawk/pull/233

thx for your help!

2021-02-10 10:51 UTC, closed without merging

2021-02-10 11:01 UTC, Alix82 commented
But AFAIK, the system call returns boolean value, so the call to 

system(...).scan() results in 

NoMethodError (undefined method `scan' for true:TrueClass)

Am I missing something?

2021-02-10 11:32 UTC, MalloZup commented
@Alix82 ok thx for remark. I'm on the way to test this

we can't use `%x` call for another issue. so will need to figure out how we can improve this.. anyways right now there is no RPM generation etc so everything is still "devel"